source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AppResizer_Example', :exclusive => true do
  pod "AppResizer", :path => "../"
end

target 'AppResizer_Tests', :exclusive => true do
  pod "AppResizer", :path => "../"

  
end
